name: Run format.sh script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip

      - name: Install ruff
        run: |
          pip install ruff

      - name: Run format.sh script
        run: |
          ruff format src/server/app --line-length 100
          ruff format src/server/tests --line-length 100
