name: Run format.sh script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip

      - name: Install ruff
        run: |
          . venv/bin/activate
          pip install ruff

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run format.sh script
        run: |
          chmod +x src/server/format.sh
          ./src/server/format.sh
